<a href="https://colab.research.google.com/github/iam-pattan/DL-lab/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## LAB-3

Using MNIST dataset


In [ ]:
import tensorflow as tf

In [ ]:
 (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
 (x_train.shape, y_train.shape), (x_test.shape, y_test.shape)

(((60000, 28, 28), (60000,)), ((10000, 28, 28), (10000,)))

In [ ]:
# convert image range from 0-255 to 0-1.0
x_train, x_test = x_train/255.0, x_test/255.0
x_train.shape, x_test.shape

((60000, 28, 28), (10000, 28, 28))

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.LeakyReLU(alpha=0.3),
    tf.keras.layers.Dense(10, activation="softmax")
])

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
optimizer_fn = tf.keras.optimizers.Adam(learning_rate=0.001)

In [ ]:
model.compile(optimizer=optimizer_fn,
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
history = model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4625 - accuracy: 0.8610 - val_loss: 0.1349 - val_accuracy: 0.9573
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1109 - accuracy: 0.9663 - val_loss: 0.1016 - val_accuracy: 0.9704
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0757 - accuracy: 0.9764 - val_loss: 0.0976 - val_accuracy: 0.9697
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0558 - accuracy: 0.9819 - val_loss: 0.0812 - val_accuracy: 0.9751
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0448 - accuracy: 0.9858 - val_loss: 0.0704 - val_accuracy: 0.9780
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0347 - accuracy: 0.9887 - val_loss: 0.0842 - val_accuracy: 0.9767
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0318 - accuracy: 0.9896 - val_loss: 0.0820 - val_accuracy:

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0806 - accuracy: 0.9801


[0.0806482657790184, 0.9800999760627747]

Training Accuracy of `99.36` is achieved.

Validation Accuray of `98.01` is achieved here.

#### Using cifar10

In [ ]:
import tensorflow as tf

In [ ]:
 (x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

170500096/170498071 [==============================] - 4s 0us/step


In [ ]:
 (x_train.shape, y_train.shape), (x_test.shape, y_test.shape)

(((50000, 32, 32, 3), (50000, 1)), ((10000, 32, 32, 3), (10000, 1)))

In [ ]:
# convert image range from 0-255 to 0-1.0
x_train, x_test = x_train/255.0, x_test/255.0
x_train.shape, x_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(32, 32, 3)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dense(64, activation="relu"),
    tf.keras.layers.Dense(32, activation="relu"),
    tf.keras.layers.LeakyReLU(alpha=0.3),
    tf.keras.layers.Dense(10, activation="softmax")
])

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
optimizer_fn = tf.keras.optimizers.Adam(learning_rate=0.001)

In [ ]:
model.compile(optimizer=optimizer_fn,
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
history = model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
1563/1563 [==============================] - 7s 4ms/step - loss: 2.0003 - accuracy: 0.2665 - val_loss: 1.7911 - val_accuracy: 0.3558
Epoch 2/10
1563/1563 [==============================] - 5s 3ms/step - loss: 1.7326 - accuracy: 0.3759 - val_loss: 1.6815 - val_accuracy: 0.4058
Epoch 3/10
1563/1563 [==============================] - 5s 4ms/step - loss: 1.6430 - accuracy: 0.4132 - val_loss: 1.6006 - val_accuracy: 0.4285
Epoch 4/10
1563/1563 [==============================] - 6s 4ms/step - loss: 1.5881 - accuracy: 0.4306 - val_loss: 1.5605 - val_accuracy: 0.4402
Epoch 5/10
1563/1563 [==============================] - 6s 4ms/step - loss: 1.5529 - accuracy: 0.4448 - val_loss: 1.5692 - val_accuracy: 0.4293
Epoch 6/10
1563/1563 [==============================] - 6s 4ms/step - loss: 1.5206 - accuracy: 0.4526 - val_loss: 1.5676 - val_accuracy: 0.4332
Epoch 7/10
1563/1563 [==============================] - 5s 3ms/step - loss: 1.5070 - accuracy: 0.4620 - val_loss: 1.5171 - val_accuracy:

In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 1.5294 - accuracy: 0.4566


[1.5294157266616821, 0.45660001039505005]

Training Accuracy of `48.34` is achieved.

Validation Accuray of `45.66` is achieved here.